services:
  litellm-postgres:
    image: postgres:15
    restart: always
    env_file:
      - ${PWD}/litellm/.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  litellm:
    image: docker.litellm.ai/berriai/litellm:main-stable
    restart: always
    depends_on:
      - litellm-postgres
    ports:
      - "4000:4000"
    env_file:
      - ${PWD}/litellm/.env
    environment:
      - LITELLM_LOG=DEBUG
    volumes:
      - ./config/litellm_config.yaml:/app/config.yaml
    command: ["--config", "/app/config.yaml", "--port", "4000"]
